### ISSUE TITLE
Add fromGeojsonVt method

### ISSUE THREAD

**Issue by drnextgis** [mapbox/vector-tile-base#3]
There is convinient fromGeojsonVt method at https://github.com/mapbox/vt-pbf. Could you consider adding the same function here?

**Comment by flippmoke** [comment]
I am sorry for the terribly slow reply here, I didn't notice I had left it unanswered. There is no plan at this time to develop a `fromGeojsonVt` method anything like that. Let me explain why in a bit of detail now:

The intent of this library is to focus simply on the encoding and decoding portion of vector tiles. However, there are a lot of decisions and steps in order to actually prepare data so that it could be used for vector tiles before this step.

* Simplification
* Clipping
* Linestring and Polygon Validation/Correction
* Reprojection
* (and many other possible steps)

All of these steps and need to be done prior to this step. The intent of this library is not to support those, but at some point in the future have a different library that does all those things separately.
